data:
  n_src: 2
  sample_rate: 8000
  segment: 3
  task: sep_clean
  train_dir: data/wav8k/max/dev_test
  valid_dir: data/wav8k/max/dev_test
filterbank:
  kernel_size: 16
  n_filters: 512
  stride: 8
main_args:
  conf_path: conf_mini.yml
  exp_dir: exp/tmp
  help: null
  resume_path: null
masknet:
  bn_chan: 128
  causal: false
  hid_chan: 512
  mask_act: relu
  n_blocks: 8
  n_repeats: 3
  n_src: 2
  skip_chan: 128
optim:
  lr: 0.001
  optimizer: adam
  weight_decay: 0.0
positional arguments: {}
training:
  batch_size: 5
  early_stop: true
  epochs: 10
  half_lr: true
  num_workers: 4
