# filterbank config
filterbank:
  n_filters: 512
  kernel_size: 40
  stride: 8
# Network config
masknet:
  n_blocks: 8
  n_repeats: 3
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
  causal: True
  norm_type: cLN
# Training config
training:
  epochs: 100
  batch_size: 10
  num_workers: 1
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  task: sep_clean
  train_dir: /dtu-compute/LibriMix/rmth/data/wav8k/max/train-100
  valid_dir: /dtu-compute/LibriMix/rmth/data/wav8k/max/dev
  sample_rate: 8000
  n_src: 2
  segment: 4
